# Default values for pretix.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

masterAdminPassword: admin  # this is the password on the first run for admin@localhost
replicaCount: 1
pvcpretix:
  storage: 512Mi
postgresql:
  storage: 1Gi
  postgreuser: pretixuser
  postgrepass: pretixpass
  postgredb: pretixdb

image:
  repository: highcanfly/pretix
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  startingTime: 60

smtpd:
  cloudflareApiKey: ""
  cloudflareDnsRecords: ""
  cloudflareZoneId: ""
  ports:
  - name: "25"
    port: 25
    targetPort: 25
  postfixHostname: ""
  replicas: 1
  smtpd:
    image:
      repository: highcanfly/smtp-relay
      tag: latest
    resources:
      limits:
        cpu: 900m
        memory: "322122547"
  smtpdAllowedSenderDomains: ""
  smtpdDkimPrivateKey: ""
  smtpdDkimSelector: ""
  smtpdPostfixHotname: ""
  smtpdRelayHost: null    # "[smtp.gmail.com]:587"
  smtpdRelayHostUsername: null # "toto@gmail.com"
  smtpdRelayHostPassword: null # gmail application pssword
  smtpdPostfixTlsSecurity: null # encrypt

  type: ClusterIP
  
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  ingressClassName: nginx
  host: pretix.cluster.local
  clusterIssuer: cert-ca-issuer


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

DEVMODE: false