#########################################################################
# © Ronan LE MEILLAT 2023
# released under the GPLv3 terms
#########################################################################
apiVersion: v1
kind: Secret
metadata:
  annotations: {}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: pretix-credentials
data:
  password: {{ b64enc .Values.masterAdminPassword }}
type: Opaque